### ISSUE TITLE
这个方法是不行了吗？一直报错403 Forbidden: "error code: 1010"

### ISSUE THREAD

**Issue by dapeng1115** [gaboolic/cloudflare-reverse-proxy#10]
直接post “/v1/chat/completions” 是说没有api key
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
   给了api key之后报的是：403 Forbidden: "error code: 1010"，看上去是被ban了，但是直接用openai的url是可以的

**Comment by gaboolic** [comment]
那可能你的ip被ban了
