### ISSUE TITLE
这样的方法只适用于api接口的转发，不方便给无梯子用户用来浏览网站是吗？

### ISSUE THREAD

**Issue by 1738970143** [gaboolic/cloudflare-reverse-proxy#15]
例如跳转到google.com无法搜索<img width="1007" alt="image" src="https://github.com/gaboolic/cloudflare-reverse-proxy/assets/90264219/4291217f-6033-479c-87b0-9ba6314be75c">
例如跳转到github无法登陆
<img width="1440" alt="image" src="https://github.com/gaboolic/cloudflare-reverse-proxy/assets/90264219/dfeccf11-0ceb-426f-9c00-d0790852a7fe">

**Comment by gaboolic** [comment]
反代接口的
