### ISSUE TITLE
添加路由和添加自定义域名有什么区别吗

### ISSUE THREAD

**Issue by huangzhitian** [gaboolic/cloudflare-reverse-proxy#2]

**Comment by gaboolic** [comment]
我刚刚发现现在添加路由不管用了，worker里面也可以添加自定义域了（之前只有添加路由）
那就都用添加自定义域好了

**Comment by huangzhitian** [comment]
> 我刚刚发现现在添加路由不管用了，worker里面也可以添加自定义域了（之前只有添加路由） 那就都用添加自定义域好了

好的大佬，但是好像chatgpt网页版的用不了是吗，就是chat.openai.com接口，是这个吗，api版接口api.openai.com测试能用

**Comment by gaboolic** [comment]
https://chat.openai.com/  可以用但是对网络环境要求非常高，这个也不对外提供接口
