### ISSUE TITLE
google代理和不添加https://前缀出错

### ISSUE THREAD

**Issue by 006lp** [gaboolic/cloudflare-reverse-proxy#21]
![Screenshot_2024-01-05-16-05-04-51_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/gaboolic/cloudflare-reverse-proxy/assets/144674902/79f75ed4-684b-464f-9737-f42c0fa2421f)

![Screenshot_2024-01-05-16-06-49-50_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/gaboolic/cloudflare-reverse-proxy/assets/144674902/7929b01e-d7aa-4197-b851-7d4a3c4dc2ed)

我的google代理出错了，尽管是https://www.google.com。
还有想问下如果不加前缀是无法访问吗？

**Comment by come105** [comment]
不加前缀当然无法访问了，数据没有经过cloudflare啊。

**Comment by 006lp** [comment]
好的谢谢
