### ISSUE TITLE
利用cloudflare-workers代理出来的api服务没办法通过流数据返回

### ISSUE THREAD

**Issue by Whyjsee** [gaboolic/cloudflare-reverse-proxy#24]
有人遇到这样的情况吗？ 利用cloudflare-workers代理出来的接口，在浏览器里调用时没办法让数据以流的形式返回了

**Comment by gaboolic** [comment]
我试过调用chatgpt流式是可以的

**Comment by Whyjsee** [comment]
> 我试过调用chatgpt流式是可以的

破案了，调试的情况下不行，调试的时候会把流的数据全部缓存起来一起返回的，但部署上去后就正常了，感谢回复~
