### ISSUE TITLE
使用进入网站时报错了

### ISSUE THREAD

**Issue by ghost** [gaboolic/cloudflare-reverse-proxy#3]
Error 1101
Worker threw exception

大佬这是咋回事呀

**Comment by gaboolic** [comment]
后面加上 proxy/网站url试试

**Comment by saajnn** [comment]
同样问题，脚本有错误

**Comment by gaboolic** [comment]
> 

我这里可以的。先看看域名是不是有问题，再找个简单的页面 get一下试试

**Comment by gaboolic** [comment]
url是什么

**Comment by MaybeQHL** [comment]
我也遇到这个错误了

**Comment by Nanqiang01** [comment]
我也遇到了同样的错误，请问解决了吗

**Comment by gaboolic** [comment]
> 后面加上 proxy/网站url试试

后面加上 proxy/网站url试试
