### ISSUE TITLE
配置成功，但 ChatGPT 显示我使用了 VPN，被 Block 了

### ISSUE THREAD

**Issue by DayuGuo** [gaboolic/cloudflare-reverse-proxy#5]
用其他网页测试，配置成功，然后测试 ChatGPT 的时候遇到了问题，被 Block 了。

**Comment by DayuGuo** [comment]
vercel 版也遇到了同样的问题

**Comment by DayuGuo** [comment]
openai的接口我没有尝试，因为之前已经设置过cloudflare worker，不是很需要。

**Comment by buxy97** [comment]
静态调用openAI API接口，然后用ChatGPT-Next-Web这个项目的桌面端配合api key就可以完美使用
