### ISSUE TITLE
请问这个可以不跳转https吗?因为国内把CF的workers.dev域名被SNI阻断了,只有http模式可用

### ISSUE THREAD

**Issue by wutongskype** [gaboolic/cloudflare-reverse-proxy#7]
请问这个可以不跳转https吗?因为国内把CF的workers.dev域名被SNI阻断了,只有http模式可用

**Comment by gaboolic** [comment]
https://secure.nom.za/

https://nic.eu.org/

https://nic.ua

搞个免费域名吧，这几个是需要申请的

**Comment by gaboolic** [comment]
dynadot.com
这个不用申请，link域名0元购买 免费一年

**Comment by wutongskype** [comment]
> dynadot.com 这个不用申请，link域名0元购买 免费一年

域名我倒是有，只不过在另外一个账号上，怕cf给封号，所以单独开了个小号来跑的哈。

这个脚本很奇怪，有时候能http有时候能https。我测试了一下，firefox系的浏览器不行，我手头的是iceweasel 112和原版，都会跳转https。而chrome系的，原版chrome和centbrowser可以在隐私窗口http使用，普通模式的不行。edge抽风，有时候http能用有时候不行。不知道是不是浏览器的原因，curl的时候可以http使用。

还是希望能支持一下http模式哈，这样使用起来方便些，适用性广点。

**Comment by gaboolic** [comment]
> > dynadot.com 这个不用申请，link域名0元购买 免费一年
> 
> 域名我倒是有，只不过在另外一个账号上，怕cf给封号，所以单独开了个小号来跑的哈。
> 
> 这个脚本很奇怪，有时候能http有时候能https。我测试了一下，firefox系的浏览器不行，我手头的是iceweasel 112和原版，都会跳转https。而chrome系的，原版chrome和centbrowser可以在隐私窗口http使用，普通模式的不行。edge抽风，有时候http能用有时候不行。不知道是不是浏览器的原因，curl的时候可以http使用。
> 
> 还是希望能支持一下http模式哈，这样使用起来方便些，适用性广点。

理论上是支持的啊，
比如https://cfproxy.xxxx.com/proxy/http:www.baidu.com
这样就是http了
你这样 会报错吗

**Comment by gaboolic** [comment]
吞链接。
```javascript
https://cfproxy.xxx.com/proxy/http://www.baidu.com
```

**Comment by wutongskype** [comment]
> > > dynadot.com 这个不用申请，link域名0元购买 免费一年
> > 
> > 
> > 域名我倒是有，只不过在另外一个账号上，怕cf给封号，所以单独开了个小号来跑的哈。
> > 这个脚本很奇怪，有时候能http有时候能https。我测试了一下，firefox系的浏览器不行，我手头的是iceweasel 112和原版，都会跳转https。而chrome系的，原版chrome和centbrowser可以在隐私窗口http使用，普通模式的不行。edge抽风，有时候http能用有时候不行。不知道是不是浏览器的原因，curl的时候可以http使用。
> > 还是希望能支持一下http模式哈，这样使用起来方便些，适用性广点。
> 
> 理论上是支持的啊， 比如https://cfproxy.xxxx.com/proxy/http:www.baidu.com 这样就是http了 你这样 会报错吗

正常模式访问会自动跳转https
![image](https://github.com/gaboolic/cloudflare-reverse-proxy/assets/40192806/4ecf61f8-9d67-425a-82a9-bc9c7dc73fdc)

隐私模式就可以, 不知道啥原因...
![image](https://github.com/gaboolic/cloudflare-reverse-proxy/assets/40192806/249ee6ec-5aeb-4bd7-8b7d-dc8ab0edea72)
