### ISSUE TITLE
使用该代理方式无法正常访问chatGPT

### ISSUE THREAD

**Issue by mingouuu** [gaboolic/cloudflare-reverse-proxy#9]
![image](https://github.com/gaboolic/cloudflare-reverse-proxy/assets/82619770/5116cad6-c911-49df-8ef3-517ed356b994)
![image](https://github.com/gaboolic/cloudflare-reverse-proxy/assets/82619770/511e871c-45fe-425c-8948-b8fa540dc2b8)
根据测试，这个服务对外访问的IP地区与前置代理有关，和WARP一样。切换到美国、新加坡、日本均出现以下提示，无法直接访问chatGPT。
![image](https://github.com/gaboolic/cloudflare-reverse-proxy/assets/82619770/097e1d23-c58a-45c1-a2fa-15f3f69fa135)

**Comment by gaboolic** [comment]
主要用它来调接口的，直接用来打开网页 弱一点

**Comment by buxy97** [comment]
可以调用接口使用GPT，接口是：https://你的域名/proxy/api.openai.com；配合chatGPT Next Web桌面端那个项目可以完美使用，不过需要GPT的api key

> ![image](https://user-images.githubusercontent.com/82619770/260683164-5116cad6-c911-49df-8ef3-517ed356b994.png) ![image](https://user-images.githubusercontent.com/82619770/260683243-511e871c-45fe-425c-8948-b8fa540dc2b8.png) 根据测试，这个服务对外访问的IP地区与前置代理有关，和WARP一样。切换到美国、新加坡、日本均出现以下提示，无法直接访问chatGPT。 ![image](https://user-images.githubusercontent.com/82619770/260683593-097e1d23-c58a-45c1-a2fa-15f3f69fa135.png)
